language: node_js
os: linux
node_js:
	- "8"
	- "10"
	- "12"
services: mongodb
env:
	- NODE_ENV=test
before_script:
	- sleep 15
after_script:
	- npm run coveralls
stages:
	- name: test
		install:
			- npm install
	- name: compatibility
		install:
			- npm install
			- npm install mongodb@2
