language: node_js
os: linux
node_js:
  - "8"
  - "10"
  - "12"
services: mongodb
env:
  - NODE_ENV=test
before_script:
  - sleep 15
after_script:
  - npm run coveralls
jobs:
  include:
    - name: compatibility
      node_js: "8"
      env:
        - NODE_ENV=test
      install:
        - npm install
        - npm install mongodb@2
