language: node_js
os: linux
node_js:
  - "13"
  - "12"
  - "10"
services: mongodb
env:
  - NODE_ENV=test
before_script:
  - sleep 15
install:
  - npm install
  - npm install multer
after_script:
  - npm run coveralls
jobs:
  include:
    - name: mongodb 2
      node_js: "10"
      env:
        - NODE_ENV=test
      install:
        - npm install
        - npm install mongodb@2
        - npm install multer
